# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000

# NOW USING MYSQL

development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_DEVELOPMENT_DB_NAME'] %>
  pool: 5
  username: <%= ENV['MYSQL_DEVELOPMENT_USER'] %>
  password: <%= ENV['MYSQL_DEVELOPMENT_PASS'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: test
  pool: 5
  username: test
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_PRODUCTION_DB_NAME'] %>
  pool: 5
  username: <%= ENV['MYSQL_PRODUCTION_USER'] %>
  password: <%= ENV['MYSQL_PRODUCTION_PASS'] %>
